import type { Metadata } from "next";
import { Alata } from "next/font/google";
import "./globals.css";
import HeaderComponent from "./components/headercomp/page";

const inter = Alata({
  subsets: ["latin"],
  weight:  "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <HeaderComponent /> {/*bu ilk sayfada gözükmeyecek */}
        {children}</body>
    </html>
  );
}
