import type { Metadata } from "next";
import { Alata } from "next/font/google";
import "./globals.css";
import HeaderComponent from "./components/headercomp/page";

const inter = Alata({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  showHeader = true,
}: Readonly<{
  children: React.ReactNode;
  showHeader?: boolean;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {showHeader && <HeaderComponent />}
        {children}
      </body>
    </html>
  );
}
